### ISSUE TITLE
 Enhancements 

### ISSUE THREAD

**Issue by happinessk** [happinessk/AWS-Custom-CRM#5]
Here are a list of enhancements to help create a better user experience
- [x] welcome screen should have some information about what the user should expect 
- [x] Upload should indicate what type of files are only accepted 
- [x] File upload screen should have more content to focus on what should happen when they upload and what happens next 

anything else?

**Comment by msiebrandeis** [comment]
I probably won't be able to code this one because the wordpress account is shared, and additionally the db is local and I can't access it inside the instance for some reason:
"conformation email after uploading"

**Comment by happinessk** [comment]
@msiebrandeis no worries. I went ahead and made the enhancements changes to focus on the user's needs.

**Comment by happinessk** [comment]
Additional changes I made :

1. allow users to submit more that one file 
2. Submit only .csv files - originally users could also submit .tsv
3. changed file label to "Upload  Lead Lists" 
4. change submit button to " Submit Lead Lists" 
5. Removed the experience of the user to have to click a link to get to the file page. 
6. created content on the page focused on our users' task 

You can visit the main page of the site to see the changes. 

Removed the following enhancement as a requirement since the user doesn't give us an email for us to follow up with them: 
`conformation email after uploading `

Food for thought: Perhaps this can be a future enhancement ... so some things we can think about - do we care who uploads the files? (this presents a security risk) can we say that the site is under a firewall and they can upload it only through there? will event marketers need to go back to the office to upload their document? do we know who uploaded the file based on user login? should user login be a future enhancement?  - just some thoughts

**Comment by happinessk** [comment]
@msiebrandeis thoughts on if we should increase the file size? I feel like this would be a good option to increase it to even 5 or more based on market needs. Thoughts?

**Comment by happinessk** [comment]
Things to note for our discussions @msiebrandeis - 
 - The file size is mainly because of Amazon SES restricting us to only verified email addresses.
 -  We could do the following proposed enhancements for the next iteration: 
 -  _`User login: so some things we can think about - do we care who uploads the files? (this presents a security risk) can we say that the site is under a firewall and they can upload it only through there? will event marketers need to go back to the office to upload their document? do we know who uploaded the file based on user login?`_
 - `error handling language`

**Comment by happinessk** [comment]
@msiebrandeis closing this card and breaking down this card to tasks on the project board.
